### ISSUE TITLE
Doesn't work with Sprockets 3.0

### ISSUE THREAD

**Issue by bryanlarsen** [metaskills/less-rails#103]
Sprockets 3.0 was released recently.   Unfortunately less-rails doesn't work with it.

```
NoMethodError: undefined method `register_preprocessor' for nil:NilClass
/home/blarsen/.rvm/gems/ruby-2.2.0/gems/less-rails-2.6.0/lib/less/rails/railtie.rb:22:in `block in <class:Railtie>'
/home/blarsen/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/blarsen/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
```

**Comment by simi** [comment]
use latest 2.7.0 version released recently

**Comment by edbond** [comment]
:ok:
```
/home/eduard/.gem/ruby/2.2.3/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /home/eduard/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/eduard/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/eduard/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/eduard/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/eduard/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/eduard/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
```

**Comment by versilov** [comment]
Same with me.

**Comment by Darwinium** [comment]
Same(

**Comment by kinkou** [comment]
Same

**Comment by spaquet** [comment]
same with me

**Comment by robotex82** [comment]
Same here

**Comment by blackmorekwb** [comment]
using 2.7.0; still getting this error though.

**Comment by Darwinium** [comment]
I've fixed it. But it's a bad solution))

Just add to /config/application.rb
```YOURAPPNAME::Application.assets = Sprockets::Railtie.build_environment(YOURAPPNAME::Application, true)```

Don't forget change YOURAPPNAME to your App name

**Comment by ylecuyer** [comment]
Same here

**Comment by simi** [comment]
try this PR please https://github.com/metaskills/less-rails/pull/112

**Comment by shaimo** [comment]
I'm having the same issue... Downgrade Sprockets?

**Comment by simi** [comment]
@shaimo please try for now

```ruby
gem 'less-rails', github: 'metaskills/less-rails'
```

New release will be ready soon.

**Comment by qsun** [comment]
@simi works for me. Thanks

**Comment by bradchaiken** [comment]
Works. Thank you.

**Comment by chrismitchell** [comment]
Thanks @simi that worked out great. Any idea when the next release will be?

**Comment by simi** [comment]
@chrismitchell released as 2.7.1

**Comment by chrismitchell** [comment]
@simi awesome thanks again

**Comment by robotex82** [comment]
2.7.1 fixed the problem for me. Thank you!
